This internship was conducted within Barid Al-Maghrib in a context characterized by the coexistence of large volumes of operational data and information systems primarily designed for transaction processing rather than analytical exploitation. The study focused on outgoing international mail flows, a domain whose variability directly impacts transport planning, workload distribution, and resource allocation.

The work carried out throughout the internship addressed the complete forecasting process, from data acquisition to the visualization of forecasting results. Due to the absence of dedicated analytical infrastructures and standardized extraction interfaces, particular attention was devoted to the development of robust data engineering procedures capable of reconstructing a coherent historical dataset from heterogeneous operational sources.

A forecasting framework aligned with the CRISP-DM methodology was subsequently designed and implemented. Several families of forecasting approaches were investigated, including statistical models, machine learning algorithms, and deep learning architectures. Their performances were assessed through a rolling-origin cross-validation strategy using multiple complementary evaluation metrics.

The experimental results demonstrated that neural forecasting approaches achieved the best performances for the four-week forecasting horizon considered in this study. In particular, the BiTCN architecture consistently outperformed competing methods according to all evaluation metrics. At the same time, additional experiments highlighted the importance of adapting model selection to the forecasting horizon, as statistical models exhibited greater stability for long-term extrapolation tasks.

Beyond forecasting performance, the proposed solution also integrates hierarchical reconciliation techniques and an interactive visualization layer developed using Altair. This component enables users to explore reconciled forecasts dynamically, compare forecasting models, and analyze shipment flows at different aggregation levels. The resulting system therefore constitutes a practical decision-support tool that bridges the gap between operational information systems and predictive analytics.

From a personal perspective, this internship provided an opportunity to consolidate competencies acquired during the engineering curriculum while gaining practical experience in a real industrial environment. It involved addressing challenges related to data extraction, time-series modeling, software integration, and the communication of analytical results to operational stakeholders.

Several perspectives can be envisaged to extend the present work. Future developments may include the incorporation of external explanatory variables, experimentation with alternative reconciliation techniques, the implementation of probabilistic forecasting approaches, and the integration of the proposed pipeline into existing business intelligence ecosystems within Barid Al-Maghrib.

Overall, this internship illustrates how modern data engineering practices and forecasting methodologies can contribute to improving visibility over postal demand and support the ongoing digital transformation initiatives undertaken by Barid Al-Maghrib.