#import "@preview/mmdr:0.2.2": mermaid


The operationalization phase defines how the forecasting system is executed in practice and how model outputs are transformed into usable operational artifacts. In the CRISP-DM framework, this stage bridges the gap between modeling results and their integration into decision-support workflows @crispdm.

In the context of this internship, operationalization is not limited to deployment in a production environment, but rather focuses on the design of a reproducible pipeline capable of generating forecasts, reconciling hierarchical outputs, and producing structured datasets for analysis and visualization.

=== Forecast Generation Pipeline

The forecasting pipeline is organized as a multi-stage process that transforms preprocessed time series into future predictions.

The process is composed of the following steps:

- preparation of hierarchical time series inputs;
- generation of root-level forecasts;
- projection of exogenous features when required;
- application of trained forecasting models;
- generation of multi-horizon predictions (h = 4 for evaluation, h = 100 for operational planning).

This pipeline is implemented in a modular way in order to support multiple model families, including statistical, machine learning, and neural forecasting approaches.

The root-level forecasting strategy is consistent across all model families, ensuring comparability of results before hierarchical reconciliation is applied.

=== Hierarchical Reconciliation Output

Raw forecasts generated by the different models are not directly suitable for operational use due to inconsistencies across hierarchical levels. In particular, independently generated forecasts do not satisfy aggregation constraints across deposit centers and destination groups.

To address this issue, a hierarchical reconciliation step is applied after forecast generation.

The reconciliation procedure follows a top-down allocation strategy based on historical proportions@top_down_paper. Let:

$
hat(y)_(i,t+h)=p_i hat(y)_("Total",t+h)
$

where:

- $hat(y)_("Total",t+h)$ represents the forecast at the aggregate level;
- $p_i$ represents the historical proportional contribution of node $i$;
- $hat(y)_(i,t+h)$ is the reconciled forecast for node $i$.

This procedure ensures structural consistency across all levels of the hierarchy while preserving the dynamics captured at the aggregate forecasting level.

The implementation is based on the HierarchicalForecast library, which provides utilities for defining hierarchical structures and applying reconciliation methods @hierarchicalforecast.

@fig-reconciliation-flow illustrates the transformation from raw model outputs to coherent hierarchical forecasts.

#figure(
  mermaid(
"
flowchart LR

A[Model Forecasts (Unstructured)]
B[Aggregate Forecast (Root Level)]
C[Top-Down Allocation]
D[Hierarchical Proportions]
E[Coherent Hierarchical Forecasts]

A --> B
B --> C
D --> C
C --> E
"
  ),
  caption: [Hierarchical reconciliation applied to model outputs.]
) <fig-reconciliation-flow>

@fig-reconciliation-flow shows that reconciliation is applied as a post-processing step after forecast generation. This ensures that all hierarchical constraints are satisfied while maintaining consistency with the root-level predictive signal.

=== Output Data Schema and Export Layer

Once forecasts are reconciled, results are structured into a unified dataset suitable for analysis, evaluation, and visualization.

The final dataset includes:

- time index (ds);
- hierarchical identifiers (deposit center, destination, or aggregated node);
- observed values (for evaluation periods);
- predicted values (for all models);
- reconciled forecasts;
- model metadata.

This structured format allows direct integration with evaluation routines as well as visualization tools.

=== Interactive Visualization System (Altair Export Layer)

An interactive visualization layer was developed to support exploratory analysis and operational interpretation of forecasts.

The system is based on Altair and provides dynamic filtering capabilities across hierarchical dimensions.

The visualization pipeline is structured as follows:

- conversion of Polars dataframes to Pandas for compatibility with Altair;
- generation of time-series plots for observed and forecasted values;
- synchronization of multiple model outputs within a single view;
- integration of dropdown filters for hierarchical navigation;
- rendering of interactive web-based charts.

The visualization layer was designed to expose reconciled forecasts generated by all evaluated forecasting models. This design enables analysts to compare forecasting behaviors interactively and assess the impact of model selection at different aggregation levels.

Rather than being restricted to a single forecasting approach, the visualization system acts as a generic interface over the forecasting outputs produced during the evaluation phase.

@fig-altair-architecture illustrates the structure of the visualization system.

#figure(
  placement: auto,
  mermaid(
"
flowchart TD

A[Reconciled Forecast Dataset]
B[DataFrame Conversion (Polars → Pandas)]
C[Altair Encoding Layer]
D[Interactive Time-Series Charts]
E[Dropdown Filters (Hierarchy Navigation)]
F[Web-Based Visualization Output]

A --> B --> C --> D --> F
C --> E --> D
"
  ),
  caption: [Architecture of the interactive Altair visualization system.]
) <fig-altair-architecture>

@fig-altair-architecture shows how reconciled forecasts are transformed into an interactive visualization. The system enables filtering across hierarchical levels while maintaining synchronization between observed values and multiple forecasting outputs.