#import "@preview/mmdr:0.2.2": mermaid
#import "@preview/zebraw:0.6.3": *
#show: zebraw


This section presents examples of forecasts generated by the proposed system. Two forecasting horizons are considered. The first corresponds to the operational horizon used throughout model evaluation and decision support activities, namely four weeks ahead. The second illustrates the behavior of the models over an extended horizon of one hundred weeks and is mainly intended for exploratory analysis and long-term trend visualization.

The forecasts presented in this section are obtained after applying the hierarchical reconciliation procedure described in Section 3.6. Consequently, predictions are coherent across all aggregation levels and can be explored either at the global level or for specific deposit centers and destination countries.

=== Short-term Forecasts (h = 4)

Short-term forecasts constitute the primary objective of this internship, as they align with the operational planning cycle identified during the business understanding phase.

Predictions generated over a four-week horizon can support several activities, including:

- transport capacity planning;
- workforce allocation;
- sorting center workload anticipation;
- monitoring of expected shipment volumes.

An example of a reconciled four-week forecast is shown in @fig-short-term-fc.

#figure(
image("../../images/short_term_forecast.svg"),
caption: [Example of a reconciled four-week forecast using the Ridge method.]
) <fig-short-term-fc>

@fig-short-term-fc illustrates the evolution of observed shipment volumes together with the predicted values produced by the selected forecasting model. The forecast follows the recent dynamics of the series while preserving consistency with the hierarchical structure.

The relatively short prediction horizon limits uncertainty accumulation and corresponds to the practical requirements expressed by operational stakeholders.

=== Extended Forecasts (h = 100)

Although model evaluation is performed using a four-week horizon, longer forecasts can also be generated by the system.

In this study, forecasts extending one hundred weeks into the future were produced for exploratory purposes. These forecasts are not intended to support detailed operational decisions but provide useful insights regarding long-term trends and seasonality persistence.

An example is presented in @fig-long-term-fc.

#figure(
image("../../images/long_term_forecast.svg"),
caption: [Example of an extended forecast over one hundred weeks. This is the same forecast as @fig-short-term-fc]
) <fig-long-term-fc>

@fig-long-term-fc shows that extending the forecasting horizon substantially increases uncertainty. While seasonal structures and global trends may still be visible, individual fluctuations become progressively harder to anticipate.

Such forecasts should therefore be interpreted cautiously and are better suited for exploratory analyses than for tactical planning activities.

=== Forecast Coherence Across Hierarchical Levels

One advantage of the proposed approach lies in the ability to generate coherent forecasts simultaneously at multiple aggregation levels.

Examples include:

- total outgoing international mail;
- individual deposit centers;
- destination countries;
- combinations of deposit centers and destinations.

The reconciliation process guarantees that lower-level predictions remain compatible with aggregated forecasts.

The forecast associated with the deposit center located in Rabat is shown in @fig-rabat-forecast.

#figure(
image("../../images/rabat_forecast.svg"),
caption:[
Forecast for the Rabat deposit center after hierarchical reconciliation.
]
) <fig-rabat-forecast>

@fig-rabat-forecast illustrates the temporal evolution of outgoing shipments originating from Rabat. The reconciled forecast remains compatible with the total forecast while preserving local dynamics specific to this center.


The forecast corresponding to shipments destined for the United States is presented in @fig-usa-forecast.

#figure(
image("../../images/usa_forecast.svg"),
caption:[
Forecast for shipments destined to the United States.
]
) <fig-usa-forecast>

@fig-usa-forecast highlights the demand dynamics associated with one of the major international destinations observed in the dataset. Such forecasts can support transport planning and resource allocation decisions for destination-specific flows.


Finally, a more granular example involving shipments deposited in Rabat and destined for the United States is shown in @fig-rabat-usa-forecast.

#figure(
image("../../images/rabat_usa_forecast.svg"),
caption:[
Forecast for shipments from Rabat to the United States.
]
) <fig-rabat-usa-forecast>

@fig-rabat-usa-forecast demonstrates the ability of the proposed system to operate at the lowest level of the hierarchy. Although such series are generally noisier and contain fewer observations, reconciliation guarantees that their forecasts remain coherent with higher aggregation levels.


These examples illustrate the flexibility of the forecasting framework. Users can explore predictions at the national level, for individual deposit centers, for destination countries, or for specific origin-destination pairs without violating aggregation constraints.

The availability of coherent forecasts at multiple levels is particularly valuable in operational settings, where planning decisions may be taken by regional managers, international logistics teams, or central management. To facilitate this exploration process, an interactive visualization interface was developed and is presented in the next section.
