#import "@preview/mmdr:0.2.2": mermaid
#import "@preview/zebraw:0.6.3": *
#show: zebraw


This section presents examples of forecasts generated by the forecasting pipeline. The objective is not to compare forecasting models, as this was addressed in @section_realization_eval_results, but rather to illustrate the types of outputs produced by the system and their suitability for operational use.

Two forecasting horizons were considered. The first corresponds to the four-week planning horizon retained for operational decision-making, while the second illustrates the behavior of models over a significantly longer extrapolation period.

=== Short-term Forecasts (h = 4)

The primary objective of this study is to support short-term planning activities within Barid Al-Maghrib. Consequently, the forecasting horizon adopted throughout the evaluation process corresponds to four weeks ahead.

Forecasts generated over this horizon can support several operational activities, including:

- Allocation of transportation capacities;
- Anticipation of sorting center workloads;
- Human resource planning;
- Monitoring expected fluctuations in international shipment volumes.

@fig-short-term-forecast presents an example of a four-week forecast generated by the system.

#figure(
  image("../../images/short_term_forecast.svg", width: 100%),
  caption: [
    Example of a four-week forecast of package count produced by the forecasting pipeline.
  ],
)<fig-short-term-forecast>

As shown in @fig-short-term-forecast, the forecasting system extends the historical trajectory while preserving the main seasonal characteristics observed in the training data. The relatively short prediction horizon limits uncertainty accumulation and allows complex models such as BiTCN to exploit local temporal patterns effectively.

For operational use, this forecasting horizon represents the most relevant scenario, since planning decisions at Barid Al-Maghrib are generally performed over relatively short time intervals.

=== Extended Forecasts (h = 100)

Although the forecasting problem addressed in this internship focuses primarily on short-term planning, additional experiments were conducted using an extended forecasting horizon of one hundred weeks.

The objective of these experiments was to analyze the stability of different forecasting approaches when producing long-range extrapolations.

@fig-long-term-forecast illustrates an example of forecasts generated over an extended horizon.

#figure(
image("../../images/long_term_forecast.svg", width:100%),
caption:[
Example of forecasts of package count generated over a horizon of one hundred weeks.
]
)
<fig-long-term-forecast>

The results indicate significant differences between forecasting families.

Neural forecasting models, particularly BiTCN and NHITS, demonstrated excellent performances for short-term predictions but tended to exhibit increasing instability as the forecasting horizon expanded. Small deviations introduced during the first predicted periods progressively accumulated, leading to trajectories that became less realistic over time.

Conversely, statistical models such as AutoARIMA and CES generally produced smoother and more stable long-term forecasts. Although their short-term accuracy was lower than that of neural approaches, their extrapolation behavior appeared more robust for horizons substantially exceeding the operational requirements considered in this study.

These observations reinforce the importance of aligning model selection with the intended forecasting horizon. Since the objective of this internship is to support four-week operational planning cycles, the superior short-term performances of BiTCN justify its recommendation despite its weaker long-range behavior.


=== Forecast Coherence Across Hierarchical Levels

One advantage of the proposed approach lies in the ability to generate coherent forecasts simultaneously at multiple aggregation levels.

Examples include:

- total outgoing international mail;
- individual deposit centers;
- destination countries;
- combinations of deposit centers and destinations.

The reconciliation process guarantees that lower-level predictions remain compatible with aggregated forecasts.

The forecast associated with the deposit center located in Rabat is shown in @fig-rabat-forecast.

#figure(
image("../../images/rabat_forecast.svg"),
caption:[
Forecast for the Rabat deposit center after hierarchical reconciliation.
]
) <fig-rabat-forecast>

@fig-rabat-forecast illustrates the temporal evolution of outgoing shipments originating from Rabat. The reconciled forecast remains compatible with the total forecast while preserving local dynamics specific to this center.


The forecast corresponding to shipments destined for the United States is presented in @fig-usa-forecast.

#figure(
image("../../images/usa_forecast.svg"),
caption:[
Forecast for shipments destined to the United States.
]
) <fig-usa-forecast>

@fig-usa-forecast highlights the demand dynamics associated with one of the major international destinations observed in the dataset. Such forecasts can support transport planning and resource allocation decisions for destination-specific flows.


Finally, a more granular example involving shipments deposited in Rabat and destined for the United States is shown in @fig-rabat-usa-forecast.

#figure(
image("../../images/rabat_usa_forecast.svg"),
caption:[
Forecast for shipments from Rabat to the United States.
]
) <fig-rabat-usa-forecast>

@fig-rabat-usa-forecast demonstrates the ability of the proposed system to operate at the lowest level of the hierarchy. Although such series are generally noisier and contain fewer observations, reconciliation guarantees that their forecasts remain coherent with higher aggregation levels.


These examples illustrate the flexibility of the forecasting framework. Users can explore predictions at the national level, for individual deposit centers, for destination countries, or for specific origin-destination pairs without violating aggregation constraints.

The availability of coherent forecasts at multiple levels is particularly valuable in operational settings, where planning decisions may be taken by regional managers, international logistics teams, or central management. To facilitate this exploration process, an interactive visualization interface was developed and is presented in the next section.
