#import "@preview/mmdr:0.2.2": mermaid
#import "@preview/zebraw:0.6.3": *
#show: zebraw


The forecasting pipeline developed during this internship produces forecasts at multiple aggregation levels and for several forecasting models. Exploring these outputs through static figures alone rapidly becomes impractical due to the number of possible combinations between deposit centers, destination countries, forecasting horizons, and candidate models.

To facilitate forecast exploration and comparison, an interactive visualization layer was implemented using Altair@altair. This component allows users to dynamically navigate reconciled forecasts and historical observations through an intuitive filtering interface.

=== Altair Dashboard Architecture

The visualization system is designed as the final layer of the forecasting pipeline. It consumes reconciled forecasts together with historical observations and exposes an interactive interface enabling users to explore different hierarchical levels.

The overall architecture is illustrated in @fig-dashboard-architecture.

#figure(
mermaid(
"
flowchart LR

A[Historical Data]
B[Forecasting Models]
C[Hierarchical Reconciliation]

D[Display Dataset]

E[Altair Dashboard]

F[Dropdown Filters]

G[Historical Series]

H[Forecast Series]

A --> B
B --> C
C --> D
D --> E

E --> F
E --> G
E --> H
"
),
caption: [Architecture of the interactive visualization system.]
) <fig-dashboard-architecture>

@fig-dashboard-architecture shows that the dashboard is positioned at the end of the forecasting workflow. Its purpose is not to generate predictions, but rather to facilitate their interpretation and operational use.

=== Visualization Components

The visualization layer relies on Altair@altair and VegaFusion@vegafusion to efficiently handle datasets containing multiple hierarchical levels and long forecasting horizons.

The dashboard is primarily composed of two synchronized graphical elements:

- an observed series chart;
- a forecast chart.

Historical observations are represented using a line chart, while forecasted values are displayed as an additional superimposed layer.

An example of the resulting visualization is shown in @fig-altair-dashboard.

#figure(
image("../../images/altair_dashboard.png"),
caption: [Example of the Altair-based interactive forecasting interface.]
) <fig-altair-dashboard>

@fig-altair-dashboard illustrates the integration of historical observations and reconciled forecasts within a single interactive visualization. The layered representation facilitates the comparison between past dynamics and expected future values.

=== User Interaction Layer

Interactivity is implemented through dropdown menus allowing users to filter forecasts according to both hierarchical dimensions and forecasting models.

The available filters include:

- deposit center (*Centre_Agence_depot*);
- destination country (*Destination*);
- forecasting model.

The model selector enables users to visualize forecasts produced by any candidate model included in the evaluation framework, such as statistical, machine learning, or deep learning approaches.

Users can therefore navigate seamlessly between:

- national forecasts;
- agency-level forecasts;
- destination-level forecasts;
- origin-destination combinations;
- alternative forecasting models.

The filtering mechanism operates directly on the reconciled display dataset. Consequently, every visualization remains hierarchically coherent regardless of the selected aggregation level or forecasting method.

The interaction workflow is summarized in @fig-dashboard-workflow.

#figure(
mermaid(
"
flowchart TD

A[User Selection]

B[Deposit Center Filter]
C[Destination Filter]
D[Model Filter]

E[Filtered Dataset]

F[Observed Series]
G[Forecast Series]

A --> B
A --> C
A --> D

B --> E
C --> E
D --> E

E --> F
E --> G
"
),
caption:[User interaction workflow within the dashboard.]
) <fig-dashboard-workflow>

@fig-dashboard-workflow shows how user selections dynamically determine the subset of historical observations and reconciled forecasts displayed in the interface. In addition to navigating the hierarchical structure, users can directly compare forecasts generated by different candidate models without retraining or recomputing predictions.

=== Operational Role

Although developed primarily as an analytical tool, the dashboard also serves as an operational decision-support interface.

Potential use cases include:

- monitoring expected shipment volumes;
- identifying upcoming demand peaks;
- comparing candidate forecasting models;
- supporting transport planning activities;
- analyzing destination-specific trends;
- investigating local demand patterns;
- communicating forecasting results to operational teams.

By providing immediate access to coherent forecasts, the visualization layer reduces the effort required to interpret model outputs and facilitates communication between analytical teams and operational stakeholders.

Furthermore, the use of Altair@altair ensures that visualizations remain reproducible and can easily be integrated into notebooks, reports, or future web-based applications.