#import "@preview/mmdr:0.2.2": mermaid
#import "@preview/zebraw:0.6.3": *
#show: zebraw


== Interactive Visualization System

The forecasting pipeline developed during this internship does not terminate at the model inference stage. To facilitate the interpretation and exploration of forecasting results, an interactive visualization layer was implemented using Altair.

The objective of this component is to provide an intuitive interface for analyzing historical observations and reconciled forecasts at different levels of aggregation. Rather than restricting users to a single forecasting approach, the visualization system exposes the outputs generated by all evaluated models, allowing interactive comparisons and supporting exploratory analysis.

This visualization layer constitutes the final stage of the operationalization process and serves as a decision-support tool for understanding future international mail flow dynamics.

=== Altair Dashboard Architecture

The dashboard was developed using Altair@altair, a declarative statistical visualization library based on the Vega-Lite@2017-vega-lite grammar.

Unlike traditional dashboards that perform model inference on demand, the proposed system relies on forecasts generated offline during the forecasting phase. Once forecasts have been produced, transformed back to their original scale, and reconciled hierarchically, they are stored within tabular structures suitable for visualization.

@fig-dashboard-architecture illustrates the logical organization of the visualization system.

#figure(
mermaid(
"
flowchart LR

A[Historical Data]
B[Forecast Models]
C[Inverse Transformations]
D[Hierarchical Reconciliation]
E[Forecast Tables]
F[Altair Dashboard]

A --> B
B --> C
C --> D
D --> E
E --> F
"
),
caption: [Architecture of the interactive visualization system.]
)
<fig-dashboard-architecture>

As shown in @fig-dashboard-architecture, the dashboard consumes already computed forecasts. Consequently, user interactions do not trigger additional forecasting computations, resulting in fast response times and low computational requirements.

=== Visualization Components

The visualization system combines historical observations and forecasting outputs within the same graphical representation.

Historical observations are extracted from the aggregated time series used during model training, while forecasted values correspond to reconciled predictions obtained after hierarchical post-processing.

The dashboard is composed of two main visualization layers:

- A historical series represented as a line chart;
- A forecast series represented as an overlayed line chart.

These layers are combined into a single interactive visualization, enabling direct comparisons between observed and predicted trajectories.

@fig-dashboard-example presents an example of the resulting visualization.

#figure(
image("../../images/altair_dashboard.png", width:100%),
caption: [Example of the interactive forecasting dashboard.]
)
<fig-dashboard-example>

The superposition of observed and predicted values facilitates the assessment of trend continuity, seasonality preservation, and anticipated changes in future shipment volumes.


=== User Interaction Layer

The dashboard incorporates several interactive controls allowing users to explore forecasts dynamically.

Three independent selection mechanisms were implemented:

- Forecasting model selector;
- Origin agency selector;
- Destination selector.

These controls enable users to analyze forecasts at multiple hierarchical levels while simultaneously comparing the behaviors of different forecasting approaches.

Examples of possible analyses include:

- Total outgoing international flows;
- Forecasts for a specific deposit center;
- Forecasts associated with a particular destination country;
- Forecasts corresponding to a given origin–destination pair.

Selections are propagated through Altair parameter bindings and filtering mechanisms, allowing charts to update automatically without requiring additional server-side computations.

This approach provides a lightweight yet flexible exploration interface suitable for operational environments.

=== Operational Role

Beyond its visualization capabilities, the dashboard serves as a decision-support instrument capable of enhancing visibility over international mail flows.

Potential operational applications include:

- Anticipation of demand peaks;
- Capacity planning;
- Monitoring of specific international corridors;
- Comparison of alternative forecasting approaches;
- Exploration of hierarchical shipment patterns.

The possibility of interactively switching between forecasting models allows users to assess the robustness of predictions and identify situations where different modeling assumptions produce diverging trajectories.

Although the dashboard was developed primarily for analytical purposes within the scope of this internship, its architecture could be integrated into broader business intelligence initiatives and contribute to future data-driven decision-making processes within Barid Al-Maghrib.